spring:
 datasource:
   url: jdbc:mysql://localhost/steam-purchases?useSSL=false
   username: root
   password: root
 jpa:
   hibernate:
     ddl-auto: update
server:
  port: 9200
user-credentials:
  users:
    - username: steamadmin
      password: steamadmin
      authorities: ROLE_ADMIN
    - username: steamapp
      password: steamapp
      authorities: ROLE_APP